### ISSUE TITLE
PKI infrastructure

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [debops/ansible-postgresql#13]
How could I install PG without SSL support?

**Comment by drybjed** [comment]
Currently `debops.postgresql` role does not support that, but I plan to overhaul it soon for Debian Jessie and I'll try to make sure that it's possible. I plan to drop hard dependency on `debops.pki` in this role.

**Comment by Yachtsman** [comment]
Any updates here?

**Comment by drybjed** [comment]
Unfortunately not, right now I need to make Docker containers work with nginx and setup Percona for an external contractor, after that i could look into PostgreSQL... Perhaps next week if time allows.

**Comment by drybjed** [comment]
The PostgreSQL roles have been redesigned, and support for installation without `debops.pki` should be present. I'm closing this issue as resolved, @Ilya-Kuchaev please let me know if it there are still issues with this setup.
