### ISSUE TITLE
Plaintext passwords are output to the console

### ISSUE THREAD

**Issue by Feld0** [debops/ansible-postgresql#18]
When this role reaches the `Grant database privileges to PostgreSQL roles` task, any un-hashed passwords (ie. with `encrypt: False`) that task deals with are printed into the console in plaintext. How about adding `no_log` to this task?

**Comment by drybjed** [comment]
Good idea, will do that right away. Thanks!

**Comment by Feld0** [comment]
@drybjed Awesome! Thanks. 😃
