### ISSUE TITLE
Do not include @ in passwords

### ISSUE THREAD

**Issue by scibi** [debops/ansible-postgresql#23]
Right now random passwords generated by this role include `@` character. Unfortunately it causes issues when you are trying to pass database connection details to an application as an URL like this: `postgres://user:password@host:port/db_name`

I'm wondering if there is real need to include characters other than letters and digits in long passwords in all roles?  Maybe smaller character space wold be enough if the passwords are long?

**Comment by drybjed** [comment]
Yikes, you're right, forgot about URL syntax.

I think that using a small character space is counterintuitive, we want to use more characters. Unfortunately the default set used by the `lookup("password")` includes the `:` character which is common in configuration files which use the `user:password` pair.

I'll remove the `@` from the character list shortly.

**Comment by scibi** [comment]
But why we want to use more characters? Ascii letters and digits give us 62 characters. There 7 more allowed characters in the role (not including `@`). Default password length is 64, so:

62^64 = ~ 5.16e+114
69^64 = ~ 4.86e+117

But if we use only smaller character space but increase length by 2 characters we have:

62^66 = ~ 1.96e+118

So the password space is bigger and we are sure that there will be no parsing problem like this. The question is if we really need so big password space?

**Comment by drybjed** [comment]
I don't see a reason not to. Having a specific range of characters that might show up in a password is bad enough, no reason to make that passwords easier to crack by limiting the character range further.

**Comment by scibi** [comment]
But you know exact character range if you know that DebOps was used...

Maybe it would be a good idea to move this to defaults so in case of any issues with any character you can change it easily?

**Comment by drybjed** [comment]
Agreed, this can be exposed in the defaults of both roles.

**Comment by scibi** [comment]
Hi! I've just encountered another issue with current list of allowed characters in password. Role generated following password: `!$0*(51!*3.!~_c)1-869i+c2_2i(&$!.(!0()5793$c_1c28(_$($40i.2+9.2-`. As I wrote I'm providing connection parameters as an URL. And in URL `+` (plus sign) means ` ` (space)...

**Comment by drybjed** [comment]
@scibi There's still a `+` sign in the default character string you defined in the PR, is that correct? I though that you wanted to remove it?

**Comment by scibi** [comment]
Yes, it's still there because I didn't want to change the default value without your opinion. If I can change it it's no longer a problem for me. So it's up to you if you want to include `+` or not.

**Comment by drybjed** [comment]
Let's remove it, since if it shows up for someone else, it will be the same problem for them too. No need to repeat that.

**Comment by drybjed** [comment]
BTW, do you want to create a similar PR for `debops.postgresql_server` role?

**Comment by scibi** [comment]
You mean `postgresql_server__admin_password`?

**Comment by drybjed** [comment]
Yes.

**Comment by scibi** [comment]
Ok. If we are removing characters what about `$`? It can make some problems when passwords are used in shell scripts and you have to use `"` to quote instead of `'` (for example because you are generating script with series of variables and some of them include `'` inside)?

**Comment by drybjed** [comment]
Sure, might be a good idea as well. Go ahead.
